### ISSUE TITLE
Stuck in step four - Set up your Stripe account

### ISSUE THREAD

**Issue by hzy033212** [ParsePlatform/ParseStore#18]
- Using Terminal, cd into the provided CloudTest folder, and run "parse add", then select the ParseStore app you set up. 
At this step, when I use terminal to go to CloudTest folder and type "parse add". Error happens as follows:
Error talking to the Parse servers; please try again.
I have successfully follow the previous steps. And I do not know whether it is a parse server problem or my problem? Thanks!

**Comment by hramos** [comment]
That error typically refers to a server-side problem. If you consistently run into that issue even though your internet connection appears to otherwise be perfectly fine, it may be due to running an older version of the Parse binary which is not configured to talk to the current set of servers. Make sure you're running the latest version of the Parse command line utility and try again.
